In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
# original data source available at https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page)
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow'

In [4]:
url = f'{prefix}/yellow_tripdata_2021-01.csv.gz'

In [5]:
# vendor id is treated as float, pandas do this automatically due to missing values
# so wee need to specify data types
# and also tell pandas which datetime objects need parsing to avoid string types for dtime
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates
)

In [6]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [7]:
len(df)

1369765

In [8]:
# vendor id is treated as float, pandas do this automatically due to missing values
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1369765 entries, 0 to 1369764
Data columns (total 18 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   VendorID               1271413 non-null  Int64
 1   tpep_pickup_datetime   1369765 non-null  datetime64[us]
 2   tpep_dropoff_datetime  1369765 non-null  datetime64[us]
 3   passenger_count        1271413 non-null  Int64
 4   trip_distance          1369765 non-null  float64
 5   RatecodeID             1271413 non-null  Int64
 6   store_and_fwd_flag     1271413 non-null  string
 7   PULocationID           1369765 non-null  Int64
 8   DOLocationID           1369765 non-null  Int64
 9   payment_type           1271413 non-null  Int64
 10  fare_amount            1369765 non-null  float64
 11  extra                  1369765 non-null  float64
 12  mta_tax                1369765 non-null  float64
 13  tip_amount             1369765 non-null  float64
 14  tolls_amount           1369765 non-null  float64
 15  improvement_surcharge  1369765 non-null  float64
 16  total_amount           1369765 non-null  float64
 17  congestion_surcharge   1369765 non-null  float64
dtypes: Int64(6), datetime64[us](2), float64(9), string(1)
memory usage: 197.2 MB

In [9]:
!uv add sqlalchemy

Resolved 119 packages in 19ms
Checked 10 packages in 4ms

In [10]:
# needed for sqlalchemy binary
!uv add psycopg2-binary

Resolved 119 packages in 5ms
Checked 10 packages in 0.17ms

In [11]:
engine =  create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [12]:
# to sql creates db if not exists and inserts data if available
# head(0) will make sure we just create schema as we want to add
# data in  batches using iterator
df.head(0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [ ]:
 print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [ ]:
len(df)

1369765

In [ ]:
# why not to add all at once it is too big, takes too long and we don;t have any idea about progress
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=100000)

In [ ]:
df_iter

In [ ]:
!uv add tqdm

Resolved 119 packages in 954ms
Prepared 1 package in 228ms
Installed 1 package in 5ms
 + tqdm==4.68.2

In [ ]:
# use df = next(df), every call of df will iterate next chunk, but it is not very practical
# beter to use for loop
for df in df_iter:
    print(len(df))

100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
69765

In [ ]:
from tqdm.auto import tqdm

In [ ]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')b

0it [00:00, ?it/s]

In [ ]:
# https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv
# wget is not in mac by default, not worth to install it as we can use curl
!curl -L -O https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 12322  100 12322    0     0  22901      0 --:--:-- --:--:-- --:--:-- 22901

In [ ]:
# to check if csv is saved
!ls

Dockerfile           main.py              pyproject.toml
README.md            notebook.ipynb       taxi_zone_lookup.csv
docker-compose.yaml  output               useful-commands.md
ingest_data.py       pipeline.py          uv.lock

In [13]:
# turn it to df
zones = pd.read_csv('taxi_zone_lookup.csv')

In [14]:
zones.describe()

       LocationID
count  265.000000
mean   133.000000
std     76.643112
min      1.000000
25%     67.000000
50%    133.000000
75%    199.000000
max    265.000000

In [ ]:
zones.head(10)

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone
5           6  Staten Island  Arrochar/Fort Wadsworth    Boro Zone
6           7         Queens                  Astoria    Boro Zone
7           8         Queens             Astoria Park    Boro Zone
8           9         Queens               Auburndale    Boro Zone
9          10         Queens             Baisley Park    Boro Zone

In [ ]:
# don't forget to check if data types are ok
zones.info()

<class 'pandas.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   LocationID    265 non-null    int64
 1   Borough       265 non-null    str
 2   Zone          264 non-null    str
 3   service_zone  263 non-null    str
dtypes: int64(1), str(3)
memory usage: 16.9 KB

In [ ]:


pg_user = 'root'
pg_pass = 'root'
pg_host = 'localhost'
pg_port = 5432
pg_db = 'ny_taxi'
engine =  create_engine(f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}')

In [ ]:
zones.to_sql(name='zones', con=engine, if_exists='replace')

265

# Homework

In [ ]:
! curl -L -O https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1137k  100 1137k    0     0  1033k      0  0:00:01  0:00:01 --:--:-- 1034k

In [15]:
november_green_taxi_data = pd.read_parquet('green_tripdata_2025-11.parquet')

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1369765 entries, 0 to 1369764
Data columns (total 18 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   VendorID               1271413 non-null  Int64
 1   tpep_pickup_datetime   1369765 non-null  datetime64[us]
 2   tpep_dropoff_datetime  1369765 non-null  datetime64[us]
 3   passenger_count        1271413 non-null  Int64
 4   trip_distance          1369765 non-null  float64
 5   RatecodeID             1271413 non-null  Int64
 6   store_and_fwd_flag     1271413 non-null  string
 7   PULocationID           1369765 non-null  Int64
 8   DOLocationID           1369765 non-null  Int64
 9   payment_type           1271413 non-null  Int64
 10  fare_amount            1369765 non-null  float64
 11  extra                  1369765 non-null  float64
 12  mta_tax                1369765 non-null  float64
 13  tip_amount             1369765 non-null  float64
 14  tolls_amount           1369765 non-null  float64
 15  improvement_surcharge  1369765 non-null  float64
 16  total_amount           1369765 non-null  float64
 17  congestion_surcharge   1369765 non-null  float64
dtypes: Int64(6), datetime64[us](2), float64(9), string(1)
memory usage: 197.2 MB

In [18]:
november_green_taxi_data.head(10)

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.00
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.2,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.00
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.5,...,0.5,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.00
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.7,...,0.5,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.00
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.4,...,1.5,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.00
5,1,2025-11-01 00:42:13,2025-11-01 01:04:50,N,1.0,112,48,2.0,5.10,26.8,...,1.5,6.55,0.0,NaN,1.0,39.35,1.0,1.0,2.75,0.75
6,2,2025-11-01 00:05:41,2025-11-01 00:39:20,N,1.0,83,87,1.0,9.80,43.6,...,0.5,9.92,0.0,NaN,1.0,59.52,1.0,1.0,2.75,0.75
7,2,2025-11-01 00:42:14,2025-11-01 01:13:20,N,1.0,66,233,1.0,5.01,28.9,...,0.5,6.98,0.0,NaN,1.0,41.88,1.0,1.0,2.75,0.75
8,2,2025-11-01 00:03:08,2025-11-01 00:06:27,N,1.0,223,223,1.0,0.63,5.1,...,0.5,1.52,0.0,NaN,1.0,9.12,1.0,1.0,0.00,0.00
9,2,2025-11-01 00:56:33,2025-11-01 01:01:34,N,1.0,130,130,1.0,1.15,7.9,...,0.5,0.00,0.0,NaN,1.0,10.40,2.0,1.0,0.00,0.00

In [20]:
# For the trips in November 2025 (lpep_pickup_datetime between '2025-11-01' and '2025-12-01', exclusive of the upper bound), how many trips had a trip_distance of less than or equal to 1 mile?

november_green_taxi_data[
    (november_green_taxi_data['lpep_pickup_datetime'] >= '2025-11-01') &
    (november_green_taxi_data['lpep_pickup_datetime'] < '2025-12-01') &
    (november_green_taxi_data['trip_distance'] <= 1)
].count()

VendorID                 8007
lpep_pickup_datetime     8007
lpep_dropoff_datetime    8007
store_and_fwd_flag       7711
RatecodeID               7711
PULocationID             8007
DOLocationID             8007
passenger_count          7711
trip_distance            8007
fare_amount              8007
extra                    8007
mta_tax                  8007
tip_amount               8007
tolls_amount             8007
ehail_fee                   0
improvement_surcharge    8007
total_amount             8007
payment_type             7711
trip_type                7710
congestion_surcharge     7711
cbd_congestion_fee       8007
dtype: int64

In [33]:
# Which was the pick up day with the longest trip distance? Only consider trips with trip_distance less than 100 miles (to exclude data errors).
trips_within_100_miles = november_green_taxi_data[november_green_taxi_data['trip_distance'] < 100]
daily = trips_within_100_miles.set_index('lpep_pickup_datetime').resample("D").max()
daily.sort_values('trip_distance', ascending=False).head(1)

,VendorID,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
lpep_pickup_datetime,,,,,,,,,,,,,,,,,,,,
2025-11-14,6.0,2025-11-15 00:19:58,Y,5.0,264.0,265.0,6.0,88.03,610.6,7.5,1.5,28.2,29.94,NaN,1.0,612.1,3.0,2.0,2.75,0.75

In [42]:
# bigest pickup zone on 18th november, join with zone usin PULocationID to get zone name, and count trips per zone, sort descending and get first row
# firslty merge zones with taxi data to get zone names
green_taxi_with_zones = november_green_taxi_data.merge(zones[['Zone', 'LocationID']], how='left', left_on='PULocationID', right_on='LocationID') 
# lets rename zone column to avoid confusion with other zone columns
green_taxi_with_zones = green_taxi_with_zones.rename(columns={'Zone': 'Pickup_Zone'})
# drop location id as we don't need it anymore
green_taxi_with_zones = green_taxi_with_zones.drop(columns=['LocationID'])
november_18th = green_taxi_with_zones[green_taxi_with_zones['lpep_pickup_datetime'].dt.date == pd.to_datetime('2025-11-18').date()]
november_18th[november_18th['Pickup_Zone'].notnull()].groupby('Pickup_Zone').size().sort_values(ascending=False).head(1)

Pickup_Zone
East Harlem North    434
dtype: int64

In [43]:
# For the passengers picked up in the zone named "East Harlem North" in November 2025,
# which was the drop off zone that had the largest tip?

east_harlem_north = green_taxi_with_zones[green_taxi_with_zones['Pickup_Zone'] == 'East Harlem North']
east_harlem_north.merge(zones[['Zone', 'LocationID']], how='left', left_on='DOLocationID', right_on='LocationID')\
.rename(columns={'Zone': 'Dropoff_Zone'}).groupby('Dropoff_Zone')['tip_amount'].max().sort_values(ascending=False).head(1)

Dropoff_Zone
Yorkville West    81.89
Name: tip_amount, dtype: float64