In [9]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
# original data source available at https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page)
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow'

In [12]:
url = f'{prefix}/yellow_tripdata_2021-01.csv.gz'

In [25]:
# vendor id is treated as float, pandas do this automatically due to missing values
# so wee need to specify data types
# and also tell pandas which datetime objects need parsing to avoid string types for dtime
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates
)

In [13]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [8]:
len(df)

1369765

In [14]:
# vendor id is treated as float, pandas do this automatically due to missing values
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               100 non-null    Int64
 1   tpep_pickup_datetime   100 non-null    datetime64[us]
 2   tpep_dropoff_datetime  100 non-null    datetime64[us]
 3   passenger_count        100 non-null    Int64
 4   trip_distance          100 non-null    float64
 5   RatecodeID             100 non-null    Int64
 6   store_and_fwd_flag     100 non-null    string
 7   PULocationID           100 non-null    Int64
 8   DOLocationID           100 non-null    Int64
 9   payment_type           100 non-null    Int64
 10  fare_amount            100 non-null    float64
 11  extra                  100 non-null    float64
 12  mta_tax                100 non-null    float64
 13  tip_amount             100 non-null    float64
 14  tolls_amount           100 non-null    float64
 15  improvement_surcharge  100 non-null    float64
 16  total_amount           100 non-null    float64
 17  congestion_surcharge   100 non-null    float64
dtypes: Int64(6), datetime64[us](2), float64(9), string(1)
memory usage: 14.9 KB

In [15]:
!uv add sqlalchemy

Resolved 117 packages in 2.33s
Prepared 1 package in 1.12s
Installed 1 package in 18ms
 + sqlalchemy==2.0.50

In [18]:
# needed for sqlalchemy binary
!uv add psycopg2-binary

Resolved 118 packages in 517ms
Prepared 1 package in 1.77s
Installed 1 package in 2ms9.12
 + psycopg2-binary==2.9.12

In [17]:
engine =  create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [23]:
# to sql creates db if not exists and inserts data if available
# head(0) will make sure we just create schema as we want to add
# data in  batches using iterator
df.head(0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [20]:
 print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [26]:
len(df)

1369765

In [37]:
# why not to add all at once it is too big, takes too long and we don;t have any idea about progress
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=100000)

In [38]:
df_iter

In [32]:
!uv add tqdm

Resolved 119 packages in 954ms
Prepared 1 package in 228ms
Installed 1 package in 5ms
 + tqdm==4.68.2

In [31]:
# use df = next(df), every call of df will iterate next chunk, but it is not very practical
# beter to use for loop
for df in df_iter:
    print(len(df))

100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
69765

In [34]:
from tqdm.auto import tqdm

In [39]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')b

0it [00:00, ?it/s]

In [3]:
# wget is not in mac by default, not worth to install it as we can use curl
!curl -L -O https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 12322  100 12322    0     0  22901      0 --:--:-- --:--:-- --:--:-- 22901

In [4]:
# to check if csv is saved
!ls

Dockerfile           main.py              pyproject.toml
README.md            notebook.ipynb       taxi_zone_lookup.csv
docker-compose.yaml  output               useful-commands.md
ingest_data.py       pipeline.py          uv.lock

In [5]:
# turn it to df
zones = pd.read_csv('taxi_zone_lookup.csv')

In [7]:
zones.describe()

       LocationID
count  265.000000
mean   133.000000
std     76.643112
min      1.000000
25%     67.000000
50%    133.000000
75%    199.000000
max    265.000000

In [8]:
zones.head(10)

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone
5           6  Staten Island  Arrochar/Fort Wadsworth    Boro Zone
6           7         Queens                  Astoria    Boro Zone
7           8         Queens             Astoria Park    Boro Zone
8           9         Queens               Auburndale    Boro Zone
9          10         Queens             Baisley Park    Boro Zone

In [10]:
# don't forget to check if data types are ok
zones.info()

<class 'pandas.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   LocationID    265 non-null    int64
 1   Borough       265 non-null    str
 2   Zone          264 non-null    str
 3   service_zone  263 non-null    str
dtypes: int64(1), str(3)
memory usage: 16.9 KB

In [15]:


pg_user = 'root'
pg_pass = 'root'
pg_host = 'localhost'
pg_port = 5432
pg_db = 'ny_taxi'
engine =  create_engine(f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}')

In [18]:
zones.to_sql(name='zones', con=engine, if_exists='replace')

265